name: "xtts_v2"
backend: "python"
max_batch_size: 0

model_transaction_policy {
  decoupled: true
}

input [
  {
    name: "TEXT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

output [
  {
    name: "OUT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 2
    gpus: [0]
  }
]